type Tenant {
  name: String!
  templates: [Template] @relation
  users: [User] @relation
  documents: [Document] @relation
}

type User {
  email: String! @unique
  name: String!
  tenant: Tenant @relation
}

type Template {
  name: String!
  language: String!
  templateParameters: [TemplateParameter]
  documents: [Document] @relation
  tenant: Tenant @relation
}

type TemplateParameter @embedded {
  key: String!
  keyType: String!
  label: String
  placeHolder: String
}

type Document {
  name: String!
  majorVersion: Int!
  minorVersion: Int!
  tenant: Tenant @relation
  template: Template @relation
}

type Query {
  getCurrentUser: User! @resolve  
}

type Mutation {
  register(email: String!, password: String!, name: String!): User @resolver
  login(email: String!, password: String!): String! @resolver
}