type Tenant {
  name: String!
}

type User {
  email: String! @unique
  name: String!  
  tenant: Tenant @relation
}

type Template {
  name: String!
  language: String!
  tenant: Tenant! @relation
  templateParameters: [TemplateParameter]
}

type TemplateParameter @embedded {
  key: String!
  keyType: String!
  label: String
  placeHolder: String
}

type Query {
  getCurrentUser: User! @resolver
}

type Mutation {
  register(email: String!, password: String!, name: String!): User @resolver
  login(email: String!, password: String!): String! @resolver
}